name: CI - Code Verification and Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.12]
    steps:
    
      - name: Check out code
        uses: actions/checkout@v4
        with:
          
          fetch-depth: 0
      - run: echo "✅ Checked out code from the repository"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: echo "🐍 Python ${{ matrix.python-version }} setup completed"

      - name: Install dependencies
        run: |
          echo "📦 Installing dependencies..."
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install pytest pytest-xdist pytest-cov 
          echo "✅ Dependencies installed successfully"

      - name: Run tests with coverage in parallel
        run: |
          echo "🧪 Running tests with pytest and generating coverage report..."
          pytest --cov=note_api --cov-report=term-missing -n auto
          echo "✅ Test run completed with coverage report"
