name: CI - Code Verification, Tests, and Quality Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  security-events: write
  id-token: write

jobs:
  google-auth:
    name: Authenticate with Google Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/70756149774/locations/global/workloadIdentityPools/github-actions/providers/github-repos'
          service_account: 'hshn-devsecops-service-account@hs-heilbronn-devsecops.iam.gserviceaccount.com'

  test:
    uses: ./.github/workflows/test.yml

  snyk_analysis:
    needs: test
    uses: ./.github/workflows/snyk_analysis.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build:
    needs: [test, snyk_analysis]
    uses: ./.github/workflows/build.yml