name: CI - Code Verification, Tests, and Quality Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  ckages: write
  secuontents: read
  pacrity-events: write
  id-token: write


jobs:
  test:
    uses: ./.github/workflows/test.yml

  snyk_analysis:
    needs: test
    uses: ./.github/workflows/snyk_analysis.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build:
    needs: [test, snyk_analysis]
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
