name: CI - Code Verification, Tests, and Quality Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      python-version: "3.12"

  snyk_analysis:
    needs: test
    uses: ./.github/workflows/snyk_analysis.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build:
    needs: [test, snyk_analysis]
    uses: ./.github/workflows/build.yml