name: Test

on: workflow_call

# env:
#   WORKLOAD_IDENTITY_PROVIDER: 'projects/70756149774/locations/global/workloadIdentityPools/github-actions/providers/github-repos'
#   SERVICE_ACCOUNT: 'hshn-devsecops-service-account@hs-heilbronn-devsecops.iam.gserviceaccount.com'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: echo "✅ Checked out code from the repository"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: echo "🐍 Python ${{ matrix.python-version }} setup completed"

      # - name: Authenticate with Google Cloud
      #   uses: google-github-actions/auth@v2
      #   with:
      #     workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
      #     service_account: ${{ env.SERVICE_ACCOUNT }}
      
      authenticate_google: 
        uses: ./.github/workflows/authenticate_google.yml
      - name: Install dependencies
        run: |
          echo "📦 Installing dependencies..."
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install pytest pytest-xdist pytest-cov
          pip install -r requirements.txt
          echo "✅ Dependencies installed successfully"

      - name: Run tests with coverage in parallel
        run: |
          echo "🧪 Running tests with pytest and generating coverage report..."
          pytest --cov=note_api --cov-report=term-missing -n auto
          echo "✅ Test run completed with coverage report"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "✅ Coverage report submitted to Codecov"
